### PR TITLE
Question.

### PR DESCRIPTION
**Pull request by meek2100**
@brasofilo,
Don't accept this PR, but take a look at my question please as I couldn't figure out a better way to reach out directly. 

Could you take a look at my questions on one of your old answers on StackExchange?
https://wordpress.stackexchange.com/questions/51920/set-custom-name-for-generated-thumbnails/383694#383694

### CODE REVIEW

**Comment by brasofilo** [comment]
Hi meek, gotta give you credit for the most crazy way I've seen someone getting in touch, lol :)   

That's a nice piece of code and looks like it keeps working without major issues.  
I've updated my answer on WPSE but this is the Gist with the correct code:
https://gist.github.com/brasofilo/a0a9d485d2f0f65dcabed8519796fa67

**Comment by meek2100** [comment]
@brasofilo ,
Wow that was fast.  haha, I had to get creative. Thanks for updating this.

**Comment by meek2100** [comment]
@brasofilo,
Something about https://gist.github.com/brasofilo/a0a9d485d2f0f65dcabed8519796fa67 isn't working quite right.  I get all the sizes, but all of my transparent PNG images end up with black backgrounds instead of transparent ones. 

Searching about this issue online it looks like my environment has everything needed to support transparent PNGs which leads me back to something in this file isn't quite working in that specific case.

Also if I disable the plug-in that has this code then the thumbnails keep transparency. 

Here are all my version numbers and GD library info:
Wordpress: 5.6.2
WooCommerce: 5.0.0
PHP-FPM: 7.4.15

Here is all the GD info from my PHP info:
GD Support enabled
GD Version bundled (2.1.0 compatible)
FreeType Support enabled
FreeType Linkage with freetype
FreeType Version 2.9.1
GIF Read Support enabled
GIF Create Support enabled
JPEG Support enabled
libJPEG Version 6b
PNG Support enabled
libPNG Version 1.6.34
WBMP Support enabled
XPM Support enabled
libXpm Version 30411
XBM Support enabled
JIS-mapped Japanese Font Support enabled
WebP Support enabled
BMP Support enabled
TGA Read Support enabled
Directive Local Value Master Value
gd.jpeg_ignore_warning 1 1

**Comment by brasofilo** [comment]
This will require some digging and testing... 
I'll have to tackle this when I have time...
Looks like it works for 24bits PNGs but not 8bits: https://wordpress.stackexchange.com/questions/40724/png-with-transparent-background-turns-black-when-uploaded-and-resized

Solution may be here:
https://stackoverflow.com/questions/6382448/png-transparency-resize-with-simpleimage-php-class

**Pull request closed without merging**
